rhonig22/Team1FinalProject

Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scripts/KitchenScripts/Spawnpoint.cs
-Fixed code to destroy old player and spawn new player on button press.
- Reposition kitchen a UI button elements
- all pieces for player interaction are placed, could not set up scripts on some due to weird compiler issue
=> Kitchen Update

Team1FinalProject/Assets/Scripts/IngredientDemo/V1/QteButtonController.cs, Team1FinalProject/Assets/Scripts/IngredientDemo/V2/NoteScrollObject.cs, Team1FinalProject/Assets/Scripts/UXControllers/DemoStartAnimationController.cs, Team1FinalProject/Assets/Settings/UniversalRP.asset, Team1FinalProject/ProjectSettings/BurstAotSettings_WebGL.json, Team1FinalProject/ProjectSettings/CommonBurstAotSettings.json
- changed build type to WebGL
- edited some build settings
- removed some using statements that were throwing errors
=> Changes needed to make a WebGL build

Team1FinalProject/Assets/Prefabs/HitTexts/HitText_Good.prefab, Team1FinalProject/Assets/Prefabs/HitTexts/HitText_Solid.prefab, Team1FinalProject/Assets/Prefabs/Kitchen/Player.prefab, Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scenes/TitleScene.unity, Team1FinalProject/Assets/Scripts/IngredientDemo/V2/LaneScroller.cs, Team1FinalProject/Assets/Scripts/UXControllers/StarController.cs, Team1FinalProject/Assets/Scripts/UXControllers/StarController.cs.meta, Team1FinalProject/Assets/Sprites/Characters/ChefHead_Cropped.png.meta, Team1FinalProject/Assets/Sprites/Characters/Happy Chef.png.meta, Team1FinalProject/Assets/Sprites/Characters/bear.png.meta, Team1FinalProject/Assets/Sprites/Characters/bot.png.meta, Team1FinalProject/Assets/Sprites/Kitchen/FlatTop.png.meta, Team1FinalProject/Assets/Sprites/Kitchen/Fridge.png.meta, Team1FinalProject/Assets/Sprites/Kitchen/Kitchen Background.png.meta, Team1FinalProject/Assets/Sprites/Kitchen/Kitchen v1.3.png.meta, Team1FinalProject/Assets/Sprites/Kitchen/Oven-StoveTop.png.meta, Team1FinalProject/Assets/Sprites/Kitchen/prep station.png.meta, Team1FinalProject/Assets/Sprites/Menus/LB icon .png.meta, Team1FinalProject/Assets/Sprites/Menus/LB icon Missed.png.meta, Team1FinalProject/Assets/Sprites/Menus/RB icon .png.meta, Team1FinalProject/Assets/Sprites/Menus/RB icon Inactive.png.meta, Team1FinalProject/Assets/Sprites/Menus/RB icon Missed.png.meta, Team1FinalProject/Assets/Sprites/Menus/Star 0%.png.meta, Team1FinalProject/Assets/Sprites/Menus/Star 100%.png.meta, Team1FinalProject/Assets/Sprites/Menus/Star 25%.png.meta, Team1FinalProject/Assets/Sprites/Menus/Star 50%.png.meta, Team1FinalProject/Assets/Sprites/Menus/Star 75%.png.meta
- integrate kitchen art assets into the scene
- create star visualizer for the score with star assets
=> Kitchen and stars

Team1FinalProject/Assets/Prefabs/HitTexts/HitText_Perfect.prefab, Team1FinalProject/Assets/Prefabs/HitTexts/HitText_Solid.prefab, Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scripts/Managers/NoteManager.cs, Team1FinalProject/Assets/Scripts/UXControllers/HitTextUXController.cs, Team1FinalProject/Assets/Sprites/Small Food/pasta.png.meta
- Move hit texts to screenspace - overlay
- position them with an offset centered around the ingredient box
=> Hit Text Refactor

Team1FinalProject/Assets/Prefabs/Managers/GameManager.prefab, Team1FinalProject/Assets/Scripts/DataStructures.meta, Team1FinalProject/Assets/Scripts/DataStructures/PlayerData.cs, Team1FinalProject/Assets/Scripts/DataStructures/PlayerData.cs.meta, Team1FinalProject/Assets/Scripts/DataStructures/RecipeData.cs, Team1FinalProject/Assets/Scripts/DataStructures/RecipeData.cs.meta, Team1FinalProject/Assets/Scripts/Managers/MusicManager.cs, Team1FinalProject/Assets/Scripts/Managers/SaveDataManager.cs, Team1FinalProject/Assets/Scripts/Managers/SaveDataManager.cs.meta, Team1FinalProject/Assets/Scripts/Managers/SoundManager.cs
- Create data structures for the recipe list and player data
- Create Save Data Manager which saves and loads these data structures from PlayerPrefs
- Hook up flows to save and load Music/Sound volumes through the save data manager
=> Initial Save Data Manager

.gitignore, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/FriedEggRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/MeatRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/PastaRecipe.asset
- add song tracks into recipe prefabs
=> Quick bug fix

Team1FinalProject/Assets/Prefabs/Kitchen/KitchenBackground.prefab, Team1FinalProject/Assets/Prefabs/Kitchen/KitchenBackground.prefab.meta, Team1FinalProject/Assets/Scenes/IntroStoryScene.unity, Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scripts/KitchenScripts/KitchenBackgroundRenderer.cs, Team1FinalProject/Assets/Scripts/KitchenScripts/KitchenBackgroundRenderer.cs.meta
- a prefab to hold the kitchen background
=> Kitchen Background Prefab

Team1FinalProject/Assets/GhostNote.cs, Team1FinalProject/Assets/Input.meta, Team1FinalProject/Assets/Prefabs/Kitchen/Player.prefab, Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scripts/UXControllers/KitchenUXController.cs, Team1FinalProject/Packages/manifest.json, Team1FinalProject/Packages/packages-lock.json, Team1FinalProject/ProjectSettings/ProjectSettings.asset
- Added Input System Package
- player can navigate buttons using WASD, Joystick, or D-Pad
- (untested on gamepad) Player sprite will spawn on press of WASD or D-Pad
- Main menu button in kitchen scene pulled out of UI navigation, currently coded to Escape key to use
=> Kitchen movement update

Team1FinalProject/Assets/GhostNote.cs, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scripts/Managers/MusicManager.cs, Team1FinalProject/Assets/Scripts/Managers/NoteManager.cs, Team1FinalProject/Assets/Scripts/Managers/SoundManager.cs, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/Onion-Diced.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/Onion-Sliced.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/ScriptableIngredient.cs, Team1FinalProject/Assets/Scripts/UXControllers/SettingsUXController.cs
BUG: On miss doesn't seem to increment when you just don't press a button. Pressing the wrong button might give you a "hit".
=> Cutting boards on some assets, quieter playback on miss.

Team1FinalProject/Assets/GhostNote.cs, Team1FinalProject/Assets/Scenes/IntroStoryScene.unity, Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scenes/SettingsScene.unity, Team1FinalProject/Assets/Scripts/Managers/NoteManager.cs, Team1FinalProject/Assets/Scripts/Managers/SoundManager.cs, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/ScriptableIngredient.cs, Team1FinalProject/Assets/Scripts/UXControllers/StarController.cs
Removed a bunch of errors by checking for null first, removed debug.logs around hit/missed notes
=> Removing debug/console errors and Logging

Team1FinalProject/Assets/Scripts/Managers/SoundManager.cs, Team1FinalProject/Assets/Sprites/Characters/Back Profile.png.meta, Team1FinalProject/Assets/Sprites/Characters/Side Profile.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/Onion/onion5.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/Potato/Fried Potato.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/Potato/Skin off Potato.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/Potato/Skin on Potato.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/Potato/Sliced Potato.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/White fish/White fish fried.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/White fish/White fish seasoned and battered.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/White fish/White fish sliced.png.meta, Team1FinalProject/Assets/Sprites/Ingredients/White fish/White fish.png.meta, Team1FinalProject/Assets/Sprites/Small Food/beef_wellington.png.meta, Team1FinalProject/Assets/Sprites/Small Food/omelette.png.meta, Team1FinalProject/Assets/Sprites/Small Food/pasta.png.meta, Team1FinalProject/Assets/Sprites/Small Food/shakshuka.png.meta
Notes now play at controllable volume
Some sprite de-fuzzing (do not compress)
=> Sprite and notes update

Team1FinalProject/Assets/Prefabs/Managers/DialogManager.prefab, Team1FinalProject/Assets/Scenes/SettingsScene.unity, Team1FinalProject/Assets/Scripts/DataStructures/UnlockablesData.cs, Team1FinalProject/Assets/Scripts/DataStructures/UnlockablesData.cs.meta, Team1FinalProject/Assets/Scripts/DialogueScripts/DialogueManager.cs, Team1FinalProject/Assets/Scripts/Managers/SaveDataManager.cs, Team1FinalProject/Assets/Scripts/RecipeBookScripts/RecipeBookController.cs, Team1FinalProject/Assets/Scripts/UXControllers/IntroStoryUXController.cs, Team1FinalProject/Assets/Scripts/UXControllers/SettingsUXController.cs
- added clear data control in the settings page
- added generic unlockable data, with first time convo being one
=> Unlockables and Data Clearing

Team1FinalProject/Assets/Scripts/Managers/PlayerManager.cs, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/NoteScrollObject.cs, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/RhythmController.cs
- fix some bugs with Note Missed evaluation
=> Note Bug Fixes

Team1FinalProject/Assets/Scripts/KitchenScripts/KitchenCanvasController.cs, Team1FinalProject/Assets/Scripts/Managers/PlayerManager.cs
- fix bug causing no ingredient sprites to show up
- fix bug causing chef to move during rhythm section
=> Bug Fixes  -8/22

Team1FinalProject/Assets/SFX/button_click_sound.mp3.meta, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity
Fixed click when recipe book loads(hopefully), tried faster decompress/on load instead of on play?
=> Some button click fixes

Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipe.cs, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/BeefBourgignonRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/BeefWellingtonRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/ChickenTikkaMasalaRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/EggplantCourgettesRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/FishAndChipsRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/FriedEggRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/OmeletteRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/PastaRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/ShakshukaRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/TartTatinRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/VeggieStirfryRecipe.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/IngredientObject.cs, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/ScriptableIngredient.cs, Team1FinalProject/Assets/Scripts/UXControllers/RecipeButtonController.cs, Team1FinalProject/Assets/Scripts/UXControllers/RecipeCompletedUXController.cs
- Rather than a set 3 star score, calculate it as a percent of the max notes that the recipe has
- Also perform some MixPanel logging
=> Calculate 3 Star Score as Percentage

Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/ChoppingMushrooms_Omelette.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/Folding omelette.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/Plated-Omelette.asset
=> Fixing woopsies

Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/FishAndChipsRecipe.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/Fish&chips2.asset
=> Fixed Fish and Chips

Team1FinalProject/Assets/Prefabs/HitTexts/HitText_Good.prefab, Team1FinalProject/Assets/Prefabs/HitTexts/HitText_Perfect.prefab, Team1FinalProject/Assets/Prefabs/HitTexts/HitText_Solid.prefab, Team1FinalProject/Assets/Scripts/Managers/NoteManager.cs, Team1FinalProject/Assets/Scripts/UXControllers/HitTextUXController.cs, Team1FinalProject/Assets/VFX Animations/HitMessageStart.anim, Team1FinalProject/Assets/VFX Animations/HitMessageStart.anim.meta, Team1FinalProject/Assets/VFX Animations/HitText_Solid.controller, Team1FinalProject/Assets/VFX Animations/HitText_Solid.controller.meta
- Move the hit text, give it a backing color, and animate it in
=> Juicy Hit Text

Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/VFX Animations/GlowAnimation.anim, Team1FinalProject/Assets/VFX Animations/GlowAnimation.anim.meta, Team1FinalProject/Assets/VFX Animations/GlowContainer.controller, Team1FinalProject/Assets/VFX Animations/GlowContainer.controller.meta
- animate the appliance glow between the 2 glow sprites
=> Animating the Appliance Glow

Team1FinalProject/Assets/Prefabs/IngredientPrefabs/Fish&Chips5.prefab, Team1FinalProject/Assets/Scenes/ControlsScene.unity, Team1FinalProject/Assets/Scripts/CustomizationScripts/ScriptableCustomization.cs, Team1FinalProject/Assets/Scripts/Managers/CustomizationManager.cs, Team1FinalProject/Assets/Scripts/Managers/GameManager.cs, Team1FinalProject/Assets/Scripts/Managers/SaveDataManager.cs, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipe.cs, Team1FinalProject/Assets/Scripts/UXControllers/RecipeButtonController.cs, Team1FinalProject/Assets/Sprites/VictoryFood/Chicken&Waffle-victory.png.meta, Team1FinalProject/Assets/Sprites/VictoryFood/Eggplant and Courgettes-victory.png.meta, Team1FinalProject/Assets/Sprites/VictoryFood/Fish&Chips-victory.png.meta, Team1FinalProject/Assets/Sprites/VictoryFood/Shakshuka-victory.png.meta, Team1FinalProject/Assets/Sprites/VictoryFood/Tarte-Victory.png.meta, Team1FinalProject/Assets/Sprites/VictoryFood/Veggie Stir Fry-victory.png.meta
- fix unlock bugs
- locked by default, but press ctrl-left to unlock everything
- fix fish & chips bug
=> Unlock bug fixes

Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/LaneScroller.cs, Team1FinalProject/Assets/Scripts/UXControllers/RecipeUXController.cs
- put unlocked image on pop-up
- 2 buttons, one sets the unlock right away
=> Unlock Pop-up Image

Team1FinalProject/Assets/Prefabs/Managers/GameManager.prefab, Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scripts/Managers/NoteManager.cs, Team1FinalProject/Packages/manifest.json, Team1FinalProject/Packages/packages-lock.json
- add the cinemachine package
- create screen bounce with impulses
=> Screen Bounce with Cinemachine

Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scripts/CustomizationScripts/ScriptableCustomization.cs, Team1FinalProject/Assets/Scripts/Managers/NoteManager.cs, Team1FinalProject/Assets/Scripts/Managers/RecipeManager.cs, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipe.cs, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/EggplantCourgettesRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/FishAndChipsRecipe.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/IngredientObject.cs, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/LaneScroller.cs
- Add a double time bool flag on scriptable recipes
- doubles the speed of the scroll lane and doubles the spacing of all notes/rests/etc
- currently set for Fish & Chips and Aubergines and Corgettes
=> Double time option for Scriptable Recipes

Team1FinalProject/Assets/Prefabs/Managers/GameManager.prefab, Team1FinalProject/Assets/Scenes/ControlsScene.unity, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scenes/SettingsScene.unity, Team1FinalProject/Assets/Scenes/TitleScene.unity, Team1FinalProject/Assets/Scripts/Managers/GameManager.cs, Team1FinalProject/Assets/Scripts/Managers/NoteManager.cs, Team1FinalProject/Assets/Scripts/UXControllers/MainMenuUXController.cs, Team1FinalProject/Assets/Scripts/UXControllers/RecipeUXController.cs, Team1FinalProject/Assets/Scripts/UXControllers/SettingsUXController.cs
- background track during all non-song scenes
- star count at top of recipe page
- moved controls inside settings
- menu navigation bug fixes
=> Background Track and Star Count

Team1FinalProject/Assets/Prefabs/IngredientPrefabs/Fish&Chips1.prefab, Team1FinalProject/Assets/Prefabs/IngredientPrefabs/Pasta Plating.prefab, Team1FinalProject/Assets/Prefabs/IngredientPrefabs/Sear Filet.prefab, Team1FinalProject/Assets/Prefabs/IngredientPrefabs/SearFilet_BeefB.prefab, Team1FinalProject/Assets/Prefabs/Kitchen/Player.prefab, Team1FinalProject/Assets/Prefabs/Managers/GameManager.prefab, Team1FinalProject/Assets/Prefabs/NotePrefabs/AButton.prefab, Team1FinalProject/Assets/Prefabs/NotePrefabs/BButton.prefab, Team1FinalProject/Assets/Prefabs/NotePrefabs/XButton.prefab, Team1FinalProject/Assets/Prefabs/NotePrefabs/YButton.prefab, Team1FinalProject/Assets/Scenes/ControlsScene.unity, Team1FinalProject/Assets/Scenes/HubScene.unity, Team1FinalProject/Assets/Scenes/SettingsScene.unity, Team1FinalProject/Assets/Scenes/TitleScene.unity, Team1FinalProject/Assets/Scripts/Managers/GameManager.cs, Team1FinalProject/Assets/Scripts/Managers/PlayerManager.cs, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/NoteScrollObject.cs, Team1FinalProject/ProjectSettings/InputManager.asset
- use wasd for keyboard and switch sprites appropriately
- chef changes direction for each appliance
- dpad navigation support for all menus
- change button size for specific prefabs
=> WASD Controls and navigation fixes

Team1FinalProject/Assets/LootLockerSDK.meta, Team1FinalProject/Assets/LootLockerSDK/Resources.meta, Team1FinalProject/Assets/LootLockerSDK/Resources/Config.meta, Team1FinalProject/Assets/LootLockerSDK/Resources/Config/LootLockerConfig.asset, Team1FinalProject/Assets/LootLockerSDK/Resources/Config/LootLockerConfig.asset.meta, Team1FinalProject/Assets/Prefabs/Managers/GameManager.prefab, Team1FinalProject/Assets/Scenes/HubScene.unity, Team1FinalProject/Assets/Scenes/LeaderboardScene.unity, Team1FinalProject/Assets/Scenes/LeaderboardScene.unity.meta, Team1FinalProject/Assets/Scenes/RecipeBookScene.unity, Team1FinalProject/Assets/Scripts/DataStructures/PlayerData.cs, Team1FinalProject/Assets/Scripts/Managers/GameManager.cs, Team1FinalProject/Assets/Scripts/Managers/LeaderboardManager.cs, Team1FinalProject/Assets/Scripts/Managers/LeaderboardManager.cs.meta, Team1FinalProject/Assets/Scripts/Managers/SaveDataManager.cs, Team1FinalProject/Assets/Scripts/UXControllers/HubUXController.cs, Team1FinalProject/Assets/Scripts/UXControllers/LeaderboardUXController.cs, Team1FinalProject/Assets/Scripts/UXControllers/LeaderboardUXController.cs.meta, Team1FinalProject/Assets/Scripts/UXControllers/RecipeCompletedUXController.cs, Team1FinalProject/Packages/manifest.json, Team1FinalProject/Packages/packages-lock.json, Team1FinalProject/ProjectSettings/EditorBuildSettings.asset, Team1FinalProject/ProjectSettings/PackageManagerSettings.asset
- lootlocker package added
- leaderboard set up
- leaderboard scene created
=> Leaderboard

Team1FinalProject/Assets/Prefabs/UX/note_cursor.prefab, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/ChoppedMushrooms_BeefB.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/ChoppingCarrots.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/DicedOnion_BeefB.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/PouringWine.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/Sauce_BeefB.asset, Team1FinalProject/Assets/Scripts/RhythmLaneScripts/ScriptableIngredients/SearFilet_BeefB.asset, Team1FinalProject/Assets/VFX Animations/NoteAnimation.anim, Team1FinalProject/Assets/VFX Animations/NoteAnimation.anim.meta, Team1FinalProject/Assets/VFX Animations/NoteCursor/NoteCursor2.png.meta, Team1FinalProject/Assets/VFX Animations/NoteCursor/NoteCursor3.png.meta, Team1FinalProject/Assets/VFX Animations/NoteCursor/NoteCursor4.png.meta, Team1FinalProject/Assets/VFX Animations/NoteCursor/NoteCursor5.png.meta, Team1FinalProject/Assets/VFX Animations/NoteCursor/NoteCursor6.png.meta, Team1FinalProject/Assets/VFX Animations/NoteCursor/NoteCursor7.png.meta, Team1FinalProject/Assets/VFX Animations/NoteCursor/noteCursor1.png.meta, Team1FinalProject/Assets/VFX Animations/note_cursor.controller, Team1FinalProject/Assets/VFX Animations/note_cursor.controller.meta
- implement Vee's note cursor animation
- add names to some ingredient prefabs
=> Note Cursor Animation

Team1FinalProject/Assets/Scenes/LeaderboardScene.unity, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/BeefBourgignonRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/BeefWellingtonRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/ChickenTikkaMasalaRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/EggplantCourgettesRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/FishAndChipsRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/FriedEggRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/OmeletteRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/PastaRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/ShakshukaRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/TartTatinRecipe.asset, Team1FinalProject/Assets/Scripts/RecipeBookScripts/ScriptableRecipes/VeggieStirfryRecipe.asset, Team1FinalProject/Assets/Scripts/UXControllers/LeaderboardUXController.cs
- fix leaderboard issues
- change difficulty to 85%
=> Leaderboard Fixes

Team1FinalProject/Assets/Scenes/KitchenScene.unity, Team1FinalProject/Assets/Scenes/LeaderboardScene.unity, Team1FinalProject/Assets/Scripts/Managers/GameManager.cs, Team1FinalProject/Assets/Scripts/UXControllers/LeaderboardUXController.cs
- leaderboard highlighting fix
- kitchen scene layout change
- conversation trigger change
=> Few Minor Fixes

Team1FinalProject/Assets/Scenes/HubScene.unity, Team1FinalProject/Assets/Scripts/UXControllers/HubUXController.cs, Team1FinalProject/Assets/VFX Animations/PixelSparkle7x7-3/PixelSparkle3-1.png.meta, Team1FinalProject/Assets/VFX Animations/PixelSparkle7x7-3/PixelSparkle3-2.png.meta, Team1FinalProject/Assets/VFX Animations/PixelSparkle7x7-3/PixelSparkle3-3.png.meta, Team1FinalProject/Assets/VFX Animations/PixelSparkle7x7-3/PixelSparkle3-4.png.meta
- fix particle blurriness
- fix customization message
=> Last few bug fixes
